repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        name: Ruff lint and import sort
        language_version: python3.12
      - id: ruff-format
        name: Ruff formatter
        language_version: python3.12

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        name: Black formatter
        args:
          - "--line-length=88"
          - "--target-version=py312"
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        name: Mypy type checker
        args:
          - "--config-file=pyproject.toml"
          - "--python-version=3.12"
        language_version: python3.12
